apps/admin/urls.py
# from django.contrib import admin
from django.urls import path
from apps.admin.views.index import Index
from apps.admin.views.scheduler import Scheduler
from apps.users.views import *

app_name = 'admin'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('scheduler', Scheduler.as_view(), name='scheduler'),
    path('scheduler_single', Scheduler.scheduler_single, name='scheduler_single'),
    path('schedulers_list', Scheduler.schedulers_list, name='schedulers_list'),
    path('schedulers_delete', Scheduler.schedulers_delete,
         name='schedulers_delete'),
]

apps/users/urls.py
from django.urls import path
from apps.users import views

app_name = 'users'

urlpatterns = [
    path('register', views.Register.as_view(), name='user_register'),
    path('login', views.Login.as_view(), name='user_login'),
    path('logout', views.logout, name='user_logout')
]

aptask/urls.py
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from aptask import settings


def return_static(request, path, insecure=True, **kwargs):
    return serve(request, path, insecure, **kwargs)


urlpatterns = [
    path('users/', include('users.urls')),
    path('', include('admin.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + [re_path(r'^static/(?P<path>.*)$', return_static, name='static'),
                                 re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), ]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.
class AdminUser(AbstractUser):
    gender_choices = (
        ('male', '男'),
        ('female', '女')
    )
    nick_name = models.CharField('昵称', max_length=50, default='')
    birthday = models.DateField('生日', null=True, blank=True)
    gender = models.CharField('性别', max_length=10, choices=gender_choices, default='1')
    address = models.CharField('地址', max_length=100, default='')
    phone = models.CharField('手机号', max_length=20, null=True, blank=True, default='')
    profile_picture = models.ImageField('用户头像', blank=True, default='website/images/logo_sm.png',
                                        upload_to='images/avatars/{}/{}/{}/{}'.format(datetime.now().year,
                                                                                      datetime.now().month,
                                                                                      datetime.now().day,
                                                                                      datetime.now().hour))
    update_time = models.DateTimeField('更新时间', auto_now=True)

apps/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from apps.users.models import AdminUser
from aptask import settings
import json
from django.contrib.auth.hashers import make_password

resp_data = dict()
login_success_code = 'success'
login_success_message = '登录成功'
login_failed_code = 'failed'
login_failed_message = '登录失败'
register_success_code = 'success'
register_success_message = '注册成功'
register_failed_code = 'failed'
register_failed_message = '注册失败'
login_session_default_expiry = settings.LOGIN_SESSION_EXPIRY_DEFAULT
login_session_remember_expiry = settings.LOGIN_SESSION_EXPIRY_REMEMBER


class CustomBackend(ModelBackend):
    def authenticate(self, request, username:str='', password:str='', **kwargs):
        try:
            user = AdminUser.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password) and self.user_can_authenticate(user):
                return user
            else:
                return None
        except Exception as e:
            return None

    def user_can_authenticate(self, user):
        """
        Reject users with is_active=False. Custom user models that don't have
        that attribute are allowed.
        """
        is_active = getattr(user, 'is_active', None)
        is_staff = getattr(user, 'is_staff', None)
        can_auth = is_active and is_staff
        return can_auth or (is_active is None or is_staff is None)


class Register(View):
    @staticmethod
    def get(request):
        with open(settings.LOGIN_PUBLIC_KEY) as f:
            key = f.read().splitlines()
        public_key = ""
        for item in key:
            public_key += item
        return render(request, 'users/register.html', {'public_key': public_key})

    @staticmethod
    def post(request):
        data = request.body
        data = json.loads(data)
        resp_data['data'] = ''
        username = data.get('username', '')
        email = data.get('email', '')
        password = data.get('password', '')
        name_user = User.objects.filter(username=username)
        email_user = User.objects.filter(email=email)
        if name_user:
            resp_data['code'] = register_failed_code
            resp_data['message'] = '账号 {} 已存在'.format(username)
        elif email_user:
            resp_data['code'] = register_failed_code
            resp_data['message'] = '邮箱 {} 已绑定账号 {}'.format(
                email, email_user[0].username)
        else:
            from extra_apps.utils.createkey import decrypt_password
            password = make_password(decrypt_password(password))
            user = User(username=username, email=email,
                        password=password, is_staff=True)
            try:
                user.save()
                resp_data['code'] = register_success_code
                resp_data['message'] = register_success_message
            except Exception as e:
                print(e)
                resp_data['code'] = register_failed_code
                resp_data['message'] = register_failed_message
        return JsonResponse(resp_data, safe=False)


class Login(View):
    @staticmethod
    def get(request):
        with open(settings.LOGIN_PUBLIC_KEY) as f:
            key = f.read().splitlines()
        public_key = ""
        for item in key:
            public_key += item
        return render(request, 'users/login.html', {'public_key': public_key})

    @staticmethod
    def post(request):
        data = request.body
        data = json.loads(data)
        username = data.get('username', '')
        password = data.get('password', '')
        remember = data.get('remember', False)
        from extra_apps.utils.createkey import decrypt_password
        password = decrypt_password(password)
        user = auth.authenticate(username=username, password=password)
        resp_data = dict()
        if user:
            auth.login(request, user)
            if remember is True:
                request.session.set_expiry(
                    login_session_remember_expiry*24*60*60)
            else:
                request.session.set_expiry(
                    login_session_default_expiry*24*60*60)
            resp_data['data'] = {}
            resp_data['code'] = login_success_code
            resp_data['message'] = login_success_message
        else:
            resp_data['data'] = {}
            resp_data['code'] = login_failed_code
            resp_data['message'] = login_failed_message
        return JsonResponse(resp_data, safe=False)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', settings.LOGIN_URL))

templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}/APTask</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Python定时任务管理平台" name="description"/>
    <meta content="新蝶" name="author"/>
    <meta content="APTask,新蝶在线,Python定时任务管理平台" name="keywords"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static '/website/images/favicon.ico' %}"/>

    <!-- Bootstrap4 -->
    <link href="{% static 'website/css/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- element--ui -->
    <link href="{% static 'website/css/element-ui/theme-chalk/index.css' %}" rel="stylesheet" type="text/css"/>

    <!-- app.css -->
    <link href="{% static 'website/css/app.css' %}" rel="stylesheet" type="text/css"/>

    <!-- 引入vue框架 -->
    <script src="{% static 'website/js/vue/vue.js' %}"></script>
    <script src="{% static 'website/js/axios/dist/axios.js' %}"></script>
    <!-- 引入element组件库 -->
    <script src="{% static 'website/js/element-ui/lib/index.js' %}"></script>

    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
    <section class="section" style="padding-top:10%;">
        {% block content %}{% endblock %}
    </section>
<script src="{% static 'website/js/jquery/jquery.slim.min.js' %}"></script>
<script src="{% static 'website/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/js/CryptoJS-master/rollups/jsencrypt.js' %}"></script>
<script src="{% static 'website/js/app.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}用户登录{% endblock %}
{% block content %}
        <div id="userLogin" class="container" v-cloak>
            <el-row type="flex" align="middle" justify="center">
                <el-col :span="10">
                    <el-row type="flex" align="middle" justify="center">
                        <img style="width: 200px;" src="{% static 'website/images/logo_gitlab.png' %}">
                    </el-row>
                    <el-form label-position="left" label-width="80px" style="margin-top:20px;" :model="user">
                        <el-form-item label="账号" prop="username">
                            <el-input v-model="user.username" placeholder="输入用户名/邮箱" suffix-icon="el-icon-user"></el-input>
                        </el-form-item>
                        <el-form-item label="密码" prop="password">
                            <el-input v-model="user.password" placeholder="输入密码" show-password></el-input>
                        </el-form-item>
                        <el-form-item>
                            <el-checkbox v-model="user.remember">记住我7天</el-checkbox>
                        </el-form-item>
                        <el-form-item align="middle">
                            <el-row type="flex" justify="space-between" align="middle">
                                <el-col :span="6">
                                    <el-button type="success" @click="userLogin" icon="el-icon-position">立即登录</el-button>
                                </el-col>
                                <el-col :span="6">
                                    <el-divider>或</el-divider>
                                </el-col>
                                <el-col :span="6">
                                    <el-button type="danger" icon="el-icon-plus" @click="userRegister">注册</el-button>
                                </el-col>
                            </el-row>
                        </el-form-item>
                    </el-form>
                </el-col>
            </el-row>
        </div>
{% endblock %}
{% block javascript %}
    <script>
        let login = new Vue({
            el: '#userLogin',
            data: {
                user: {username: '', password: '', remember:false},
            },
            
            methods: {
                userLogin: function () {
                    let crypto_password = ps_encrypt(this.user.password, "{{ public_key|safe }}");
                    axios({
                        url: "{% url 'users:user_login' %}",
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                            "Access-Control-Allow-Origin": "*",
                            "X-CSRFToken": "{{ csrf_token }}"
                        },
                        data: {
                            username:this.user.username,
                            password:crypto_password,
                            remember:this.user.remember
                        },
                    }).then(response => {
                        if(response.data.code==='success'){
                            let next_url = '{{ request.GET.next }}';
                            console.log('{{ user }}');
                            if(next_url !== ''){
                                window.location.href = next_url;
                            }else{
                                window.location.href = "{% url 'admin:index' %}";
                            }
                        }else{
                            this.$notify({
                                title: '错误',
                                message: '登录失败:用户名或密码错误！',
                                type: 'error',
                                iconClass: 'el-icon-error'
                            });
                        }
                    }).catch(error => {
                        console.log(error)
                        this.$notify({
                            title: '错误',
                            message: '登录失败',
                            type: 'error',
                            iconClass: 'el-icon-error'
                        });
                    })
                },

                userRegister:function (){
                    window.location.href = "{% url 'users:user_register' %}";
                }
            }
        })
    </script>
{% endblock %}

templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}用户注册{% endblock %}
{% block content %}
<div id="userRegister" class="container" v-cloak>
    <el-row type="flex" align="middle" justify="center">
        <el-col :span="10">
            <el-row type="flex" align="middle" justify="center">
                <img style="width: 200px;" src="{% static 'website/images/logo_gitlab.png' %}">
            </el-row>
            <el-form ref="registerForm" label-position="left" :rules="rules" label-width="80px"
                style="margin-top: 20px;" :model="user">
                <el-form-item label="账号" prop="username">
                    <el-input v-model="user.username" placeholder="输入用户名" suffix-icon="el-icon-user">
                    </el-input>
                </el-form-item>
                <el-form-item label="邮箱" prop="email">
                    <el-input v-model="user.email" placeholder="输入邮箱" suffix-icon="el-icon-message">
                    </el-input>
                </el-form-item>
                <el-form-item label="密码" prop="password">
                    <el-input v-model="user.password" placeholder="输入密码" show-password></el-input>
                </el-form-item>
                <el-form-item label="确认密码" prop="confirm_password">
                    <el-input v-model="user.confirm_password" placeholder="再次输入密码" show-password></el-input>
                </el-form-item>
                <el-form-item align="middle">
                    <el-row type="flex" justify="space-between" align="middle">
                        <el-col :span="6">
                            <el-button type="success" icon="el-icon-plus" @click="userRegister('registerForm')">立即注册
                            </el-button>
                        </el-col>
                        <el-col :span="6">
                            <el-divider>或</el-divider>
                        </el-col>
                        <el-col :span="6">
                            <el-button type="danger" @click="userLogin" icon="el-icon-position">登录</el-button>
                        </el-col>
                    </el-row>
                </el-form-item>
            </el-form>
        </el-col>
    </el-row>
</div>
{% endblock %}
{% block javascript %}
<script>
    let checkUsername = (rule, value, callback) => {
        let reg = /^[a-zA-Z0-9_-]{8,40}$/;
        if (!value) {
            return callback(new Error('账号不能为空'));
        }
        setTimeout(() => {
            if (!reg.test(value)) {
                callback(new Error('请输入字母、数字、下划线、减号，长度8至40位'));
            } else {
                callback();
            }
        }, 1000);
    };
    let checkEmail = (rule, value, callback) => {
        let reg = /\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;
        if (!value) {
            return callback(new Error('请输入邮箱'));
        }
        setTimeout(() => {
            if (!reg.test(value)) {
                callback(new Error('请输入正确的邮箱'));
            } else {
                callback();
            }
        }, 1000);
    };
    let validatePassWord = (rule, value, callback) => {
        let reg = /^(?![0-9]+$)(?![a-z]+$)(?![A-Z]+$)(?!([^(0-9a-zA-Z)])+$).{6,}$/;
        if (!value) {
            callback(new Error('请输入密码'));
        }
        setTimeout(() => {
            if (!reg.test(value)) {
                callback(new Error('请至少包含字母、数字、特殊字符中的两种，长度6位以上'));
            } else {
                callback();
            }
        }, 1000);
    };
    let validateConfirmPassWord = (rule, value, callback) => {
        if (!value) {
            callback(new Error('请再次输入密码'));
        } else if (value !== register.user.password) {
            callback(new Error('两次输入密码不一致!'));
        } else {
            callback();
        }
    };
    let register = new Vue({
        el: '#userRegister',
        data: {
            user: { username: '', email: '', password: '', confirm_password: '' },
            rules: {
                username: [
                    { validator: checkUsername, trigger: 'blur' }
                ],
                email: [
                    { validator: checkEmail, trigger: 'blur' }
                ],
                password: [
                    { validator: validatePassWord, trigger: 'blur' }
                ],
                confirm_password: [
                    { validator: validateConfirmPassWord, trigger: 'blur' }
                ]
            }
        },
        methods: {
            userRegister: function (formName) {
                this.$refs[formName].validate(valid => {
                    if (valid) {

                        let crypto_password = ps_encrypt(this.user.password, "{{ public_key|safe }}");
                        axios({
                            url: "{% url 'users:user_register' %}",
                            method: 'POST',
                            headers: {
                                "Content-Type": "application/json",
                                "Access-Control-Allow-Origin": "*",
                                "X-CSRFToken": "{{ csrf_token }}"
                            },
                            data: {
                                username: this.user.username,
                                email: this.user.email,
                                password: crypto_password,
                            }
                        }).then(response => {
                            if (response.data.code === 'success') {
                                window.location.href = "{% url 'users:user_login' %}";
                            } else {
                                this.$notify({
                                    title: '警告',
                                    message: response.data.message,
                                    type: 'warning',
                                    iconClass: 'el-icon-warning'
                                });
                            }
                        }).catch(error => {
                            this.$notify({
                                title: '错误',
                                message: error,
                                type: 'error',
                                iconClass: 'el-icon-error'
                            });
                        })
                    } else {
                        return false;
                    }
                })
            },
            userLogin: function () {
                window.location.href = "{% url 'users:user_login' %}";
            },
            send_email_code: function (email) {
                axios({
                    url: "",
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "Access-Control-Allow-Origin": "*",
                        "X-CSRFToken": "{{ csrf_token }}"
                    },
                    data: {}
                }).then(response => {
                    console.log(response.message);
                }).catch(error => {
                    console.log(error);
                })
            }
        }
    })
</script>
{% endblock %}